#! /bin/bash

# Check the number of arguments provided
if [ "$#" -ne 1 ]; then
    echo "Usage:"
    echo "run.sh <base_slice>"
    exit 1
fi

mkdir -p result
mkdir -p result/$(($1/1000000))ms
BASE_DIR=result/$(($1/1000000))ms
NUM_OF_ITER=10
THREADS=104
TIME=120
MIN_GRAN=$1

# Function to create an incremented file name if it doesn't exist
create_incremented_file() {
    local base_filename="$1"  # Base name for the files
    local i=1                 # Initial increment value

    while [ -e "${base_filename}${i}" ]; do
        ((i++))
    done

    local new_file="${base_filename}${i}"
    echo "$new_file"
}

function run_ebizzy() {
	local FILE=$(create_incremented_file $OP_FILE)
	echo $MIN_GRAN > /sys/kernel/debug/sched/base_slice_ns
	cat /sys/kernel/debug/sched/base_slice_ns >> $FILE 
	#cat /proc/sys/kernel/sched_cfs_bandwidth_slice_us >> $OP_FILE
	echo 0 > /proc/sys/kernel/nmi_watchdog
	CMD="./ebizzy -t $THREADS -S $TIME" 
	echo $CMD
	perf stat -o $FILE $CMD > $FILE.ebizzy
	echo 1 > /proc/sys/kernel/nmi_watchdog
	cat $FILE.ebizzy >> $FILE
	rm $FILE.ebizzy
}
for ((j = 104; j <= 2080; j = j + 104)); do
	THREADS=$j
	mkdir -p $BASE_DIR/$THREADS
	OP_FILE=$BASE_DIR/$THREADS/exp
	for ((i = 1; i <= NUM_OF_ITER; i++)); do
		echo "Running $i iteration"
		echo "no of threads $THREADS"
		run_ebizzy
	done
done



